# Generated by Django 4.0.4 on 2022-06-06 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flc_main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='List',
            new_name='Resource',
        ),
    ]
