# Generated by Django 4.0.4 on 2022-06-06 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flc_main_app', '0002_rename_list_resource'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='img',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='created_at',
        ),
    ]
