# Generated by Django 4.0.4 on 2022-06-06 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flc_main_app', '0004_resource_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='general_pers_dev',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resource',
            name='goal_setting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resource',
            name='growth_mindset',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resource',
            name='habit_building',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resource',
            name='time_management',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resource',
            name='type_article',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resource',
            name='type_book',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resource',
            name='type_other',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resource',
            name='type_podcast',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resource',
            name='type_video',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resource',
            name='type_worksheet',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='resource',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
    ]
