# Generated by Django 4.0.4 on 2022-06-07 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flc_main_app', '0009_alter_comment_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='resource',
        ),
    ]
