# Generated by Django 4.0.4 on 2022-06-07 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flc_main_app', '0012_comment_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='title',
        ),
    ]
