# Generated by Django 4.0.4 on 2022-06-07 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flc_main_app', '0013_remove_comment_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='resource',
        ),
    ]
