# Generated by Django 4.0.4 on 2022-06-07 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flc_main_app', '0018_alter_comment_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
