# Generated by Django 4.0.4 on 2022-06-07 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flc_main_app', '0021_comment_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='authorID',
        ),
    ]
