# Generated by Django 4.0.4 on 2022-06-07 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flc_main_app', '0022_rename_author_comment_authorid'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='body',
            field=models.TextField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
