# Generated by Django 4.0.4 on 2022-06-07 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flc_main_app', '0023_comment_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resourcelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('resources', models.ManyToManyField(to='flc_main_app.resource')),
            ],
        ),
    ]
