# Generated by Django 4.0.4 on 2022-06-07 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flc_main_app', '0024_resourcelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcelist',
            name='fav_list',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resourcelist',
            name='general_pers_dev',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resourcelist',
            name='goal_setting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resourcelist',
            name='growth_mindset',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resourcelist',
            name='habit_building',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resourcelist',
            name='time_management',
            field=models.BooleanField(default=False),
        ),
    ]
