# Generated by Django 4.0.4 on 2022-06-07 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flc_main_app', '0026_rename_title_resourcelist_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcelist',
            name='image',
            field=models.CharField(default='image not available', max_length=250),
            preserve_default=False,
        ),
    ]
